# Site settings
title: STPEG
description: "South Thames Paediatric Endocrine Group - Advancing paediatric endocrinology in South East England"
baseurl: ""
url: "https://stpeg.org"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
future: true

# Collections
collections:
  events:
    output: true
    permalink: /:collection/:name/
  speakers:
    output: true
    permalink: /:collection/:name/
  meeting_minutes:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "speakers"
    values:
      layout: "speaker"
  - scope:
      path: ""
      type: "meeting_minutes"
    values:
      layout: "meeting_minute"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - _utils/
